[build]
  publish = "dist"
  command = "yarn build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "yarn dev"
  targetPort = 3000

[[redirects]]
  from = "/api/places/*"
  to = "/.netlify/functions/places/:splat"
  status = 200

[[redirects]]
  from = "/api/geodb/*"
  to = "/.netlify/functions/geodb/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; connect-src 'self' https://api.geoapify.com https://wft-geo-db.p.rapidapi.com https://ipapi.co"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"